# Generated by Django 6.0 on 2025-12-17 07:15

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': '首頁'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='橫幅圖片'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='橫幅副標題'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(default='SG44 研討會', max_length=255, verbose_name='橫幅標題'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('embed', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': '標題'}), 1: ('wagtail.blocks.RichTextBlock', (), {'icon': 'pilcrow', 'label': '段落'}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'icon': 'image', 'label': '圖片'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote', 'label': '引言'}), 4: ('wagtail.blocks.URLBlock', (), {'icon': 'media', 'label': '嵌入連結（YouTube等）'})}, verbose_name='內容區塊'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='conference_date',
            field=models.CharField(blank=True, max_length=100, verbose_name='研討會日期'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='conference_location',
            field=models.CharField(blank=True, max_length=255, verbose_name='研討會地點'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_1_icon',
            field=models.CharField(blank=True, help_text='例如：📅', max_length=50, verbose_name='特色1圖示'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_1_text',
            field=models.TextField(blank=True, verbose_name='特色1說明'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_1_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='特色1標題'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_2_icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='特色2圖示'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_2_text',
            field=models.TextField(blank=True, verbose_name='特色2說明'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_2_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='特色2標題'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_3_icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='特色3圖示'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_3_text',
            field=models.TextField(blank=True, verbose_name='特色3說明'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='feature_3_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='特色3標題'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='簡介'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='報名截止日期'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='registration_link',
            field=models.URLField(blank=True, verbose_name='報名連結'),
        ),
    ]
